In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
indep = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep = dataset[['classification_yes']]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
xtrain,xtest,ytrain,ytest = train_test_split(indep,dep,test_size=1/3,random_state=0)

In [10]:
# This block is for GaussianNB in Naive Bayes
from sklearn.naive_bayes import GaussianNB

param = {}
from sklearn.model_selection import GridSearchCV
model = GridSearchCV(GaussianNB(),param,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1,cv=5)

model.fit(xtrain,ytrain.values.ravel())
ypredict = model.predict(xtest)
model.best_params_
re = model.cv_results_
table = pd.DataFrame.from_dict(re)
table
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypredict)
from sklearn.metrics import classification_report
clfrpt = classification_report(ytest,ypredict)
print (clfrpt)
print(cm)
from sklearn.metrics import f1_score
f1 = f1_score(ytest,ypredict,average='weighted')
print (f1)
from sklearn.metrics import roc_auc_score
rocauc = roc_auc_score(ytest,model.predict_proba(xtest)[:,1])
print (rocauc)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

[[51  0]
 [ 3 79]]
0.9775556904684072
1.0

In [11]:
# This block is for MultinomialNB in Naive Bayes
from sklearn.naive_bayes import MultinomialNB
#mlnb = MultinomialNB()
param = {}
from sklearn.model_selection import GridSearchCV
model = GridSearchCV(MultinomialNB(),param,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1,cv=5)

model.fit(xtrain,ytrain.values.ravel())
ypredict = model.predict(xtest)
model.best_params_
re = model.cv_results_
table = pd.DataFrame.from_dict(re)
table
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypredict)
from sklearn.metrics import classification_report
clfrpt = classification_report(ytest,ypredict)
print (clfrpt)
print(cm)
from sklearn.metrics import f1_score
f1 = f1_score(ytest,ypredict,average='weighted')
print (f1)
from sklearn.metrics import roc_auc_score
rocauc = roc_auc_score(ytest,model.predict_proba(xtest)[:,1])
print (rocauc)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.68      0.98      0.81        51
           1       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

[[50  1]
 [23 59]]
0.8215780250262184
0.9151123864179818

In [12]:
# This block is for BernoulliNB in Naive Bayes
from sklearn.naive_bayes import BernoulliNB
#bnl = BernoulliNB()
param = {}
from sklearn.model_selection import GridSearchCV
model = GridSearchCV(BernoulliNB(),param,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1,cv=5)

model.fit(xtrain,ytrain.values.ravel())
ypredicts = model.predict(xtest)
model.best_params_
re = model.cv_results_
table = pd.DataFrame.from_dict(re)
table
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypredicts)
from sklearn.metrics import classification_report
clfrpt = classification_report(ytest,ypredicts)
print (clfrpt)
print(cm)
from sklearn.metrics import f1_score
f1 = f1_score(ytest,ypredict,average='weighted')
print (f1)
from sklearn.metrics import roc_auc_score
rocauc = roc_auc_score(ytest,model.predict_proba(xtest)[:,1])
print (rocauc)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.86      1.00      0.93        51
           1       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

[[51  0]
 [ 8 74]]
0.8215780250262184
0.9966523194643712

In [22]:
# This block is for ComplementNB in Naive Bayes
from sklearn.naive_bayes import ComplementNB
#cpl = ComplementNB()
param = {}
from sklearn.model_selection import GridSearchCV
model = GridSearchCV(ComplementNB(),param,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1,cv=5)

model.fit(xtrain,ytrain.values.ravel())
ypredict = model.predict(xtest)
model.best_params_
re = model.cv_results_
table = pd.DataFrame.from_dict(re)
table
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypredict)
from sklearn.metrics import classification_report
clfrpt = classification_report(ytest,ypredict)
print (clfrpt)
print(cm)
from sklearn.metrics import f1_score
f1 = f1_score(ytest,ypredict,average='weighted')
print (f1)
from sklearn.metrics import roc_auc_score
rocauc = roc_auc_score(ytest,model.predict_proba(xtest)[:,1])
print (rocauc)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.68      0.98      0.81        51
           1       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

[[50  1]
 [23 59]]
0.8215780250262184
0.9151123864179818